export interface Ngglobal{
   id_ngGlobal:number,
   login_status:string,
   lastname:string,
   firstname:string,
   login:string,
   mail:string,
   phone:string,
   airbus_sigle:string,
   pc_asset_number:string,
   altran_pc_series_number:string,
   account_creation_date:string,
   localisation:string,
   airbus_order_giver:string,
   contract_workpackage_number:string,
   altran_manager:string,
   request_mail_sender :string,
   anexs_zone_state:string,
   anexs_limitations:string,
   start_date:string,
   mg_validation:string,
}
